### ISSUE TITLE
v1

### ISSUE THREAD

**Issue by ohbarye** [ohbarye/pbt#26]
With the talk at [RubyKaigi 2024](https://rubykaigi.org/2024/presentations/ohbarye.html), the proof of concept has been completed. From now on, I plan to continue development by focusing on the functions necessary for a practical gem.

## TODOs

- [ ] Implement frequency arbitrary
- [ ] Statistics feature to aggregate generated values
- [ ] Decide DSL
- [ ] Try Fiber
- [ ] Stateful property-based testing
- [ ] Remove complex/unnecessary feature (multi-Process, multi-Thread, Ractor RSpec integration)

**Comment by rafamvc** [comment]
Can I help? I am interested in Property based testing, and I am a ruby dev.
